name: build

on:
  - push
  - pull_request

jobs:
  test:
    name: "Test: Rails ${{ matrix.rails }} on Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rails: "6.0"
            ruby: "2.7"

          - rails: "6.1"
            ruby: "2.7"
          - rails: "6.1"
            ruby: "3.0"
          - rails: "6.1"
            ruby: "3.1"
          - rails: "6.1"
            ruby: "3.2"

          - rails: "7.0"
            ruby: "3.1"
          - rails: "7.0b"
            ruby: "3.2"

          - rails: "7.1"
            ruby: "3.1"
          - rails: "7.1b"
            ruby: "3.1"
          - rails: "7.1.1"
            ruby: "3.2"
          - rails: "7.1"
            ruby: "3.2"

          - rails: "7.2"
            ruby: "3.3"

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
      DISPLAY: ":99.0"

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
        with:
          ruby-version: ${{ matrix.ruby }}
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Gemfile
        run: echo $BUNDLE_GEMFILE

      - name: Ruby Version
        run: ruby --version

      - name: Run Tests
        run: bundle exec rake test
